CREATE TABLE order_payments (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  payment_id BIGINT NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);
